export const INCREASE_COUNTER = "INCREASE_COUNTER";
export const DECREASE_COUNTER = "DECREASE_COUNTER";
export const GET_LATEST_NEWS = "GET_LATEST_NEWS";
export const SET_LATEST_NEWS = "SET_LATEST_NEWS";
